{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "conda install -c conda-forge sunpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T19:31:00.783056Z",
     "start_time": "2024-03-20T19:30:56.209804Z"
    }
   },
   "outputs": [],
   "source": [
    "import sunpy.map\n",
    "from sunpy.net import Fido, attrs as a\n",
    "import astropy.units as u\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T19:31:15.003940Z",
     "start_time": "2024-03-20T19:31:01.870914Z"
    }
   },
   "outputs": [],
   "source": [
    "results = Fido.search(a.Time('2015/05/08 12:00', '2015/05/17 12:00'),a.Instrument('HMI'),\n",
    "                      a.Sample(0.5*u.day),a.Physobs(\"intensity\"))\n",
    "files = Fido.fetch(results, path=\"./sunimages/\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T19:32:58.088031Z",
     "start_time": "2024-03-20T19:32:58.084749Z"
    }
   },
   "outputs": [],
   "source": [
    "# sort the file names alphabetically using the python function sorted\n",
    "# Your code here:\n",
    "files = sorted(files)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T19:32:59.019283Z",
     "start_time": "2024-03-20T19:32:59.014332Z"
    }
   },
   "outputs": [],
   "source": [
    "files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T19:33:00.359382Z",
     "start_time": "2024-03-20T19:33:00.342485Z"
    }
   },
   "outputs": [],
   "source": [
    "results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2024-03-20T19:33:03.139257Z",
     "start_time": "2024-03-20T19:33:01.714498Z"
    }
   },
   "outputs": [],
   "source": [
    "# load a sunpy Map from the first file in files (remember python indexes start at 0)\n",
    "# Hint: Use sunpy.map.Map()\n",
    "# Your code here:\n",
    "smap = sunpy.map.Map(files[0])\n",
    "\n",
    "smap = smap.resample((2048, 2048) * u.pix)\n",
    "#smap = smap.rotate(order=3)\n",
    "fig = plt.imshow(smap.data, cmap='Greys_r', origin='lower')\n",
    "plt.axis('off')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "hide_input": false,
  "kernelspec": {
   "display_name": "Python [conda env:basenew]",
   "language": "python",
   "name": "conda-env-basenew-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
